# options:
#   default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

# steps:
#   # 1️⃣ Build dell'immagine Docker
#   - name: 'gcr.io/cloud-builders/docker'
#     args:
#       [
#         'build',
#         '-t',
#         'europe-west1-docker.pkg.dev/$PROJECT_ID/sharingtv-fe/sharingtv-fe:$COMMIT_SHA',
#         '.'
#       ]

#   # 2️⃣ Push dell’immagine su Artifact Registry
#   - name: 'gcr.io/cloud-builders/docker'
#     args:
#       [
#         'push',
#         'europe-west1-docker.pkg.dev/$PROJECT_ID/sharingtv-fe/sharingtv-fe:$COMMIT_SHA'
#       ]

#   # 3️⃣ Deploy manuale verso Cloud Run (MA SENZA trigger automatico)
#   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
#     entrypoint: gcloud
#     args:
#       [
#         'run',
#         'deploy',
#         'sharing-tv-app-fe',
#         '--image=europe-west1-docker.pkg.dev/$PROJECT_ID/sharingtv-fe/sharingtv-fe:$COMMIT_SHA',
#         '--region=europe-west1',
#         '--platform=managed',
#         '--allow-unauthenticated',
#         '--port=8080'
#       ]

# images:
#   - 'europe-west1-docker.pkg.dev/$PROJECT_ID/sharingtv-fe/sharingtv-fe:$COMMIT_SHA'

